debootstrap: update to 1.0.106

diff --git a/packages/debootstrap/functions.patch b/packages/debootstrap/functions.patch
--- a/packages/debootstrap/functions.patch
+++ b/packages/debootstrap/functions.patch
@@ -1,7 +1,26 @@
-diff -u -r ../debootstrap-1.0.102/functions ./functions
---- ../debootstrap-1.0.102/functions	2018-06-13 13:00:11.000000000 +0000
-+++ ./functions	2018-06-21 20:30:41.301533374 +0000
-@@ -910,7 +910,7 @@
+diff -uNr debootstrap-1.0.106/functions debootstrap-1.0.106.mod/functions
+--- debootstrap-1.0.106/functions	2018-07-05 11:48:22.000000000 +0300
++++ debootstrap-1.0.106.mod/functions	2018-07-10 17:20:18.985640585 +0300
+@@ -220,17 +220,7 @@
+ }
+ 
+ detect_container () {
+-	if [ "$container" = lxc ]; then
+-		CONTAINER="lxc"
+-	elif grep -qs container=lxc-libvirt /proc/1/environ; then
+-		CONTAINER="lxc-libvirt"
+-	elif grep -qs ^systemd-nspawn$ /run/systemd/container || [ "$container" = "systemd-nspawn" ]; then
+-		CONTAINER="systemd-nspawn"
+-	elif grep -qs '[[:space:]]/docker/.*/sys/fs/cgroup' /proc/1/mountinfo; then
+-		CONTAINER="docker"
+-	else
+-		CONTAINER=""
+-	fi
++	CONTAINER=""
+ }
+ 
+ ########################################################## variant handling
+@@ -924,7 +914,7 @@
  extract_dpkg_deb_data () {
  	local pkg="$1"
  
@@ -10,7 +29,7 @@ diff -u -r ../debootstrap-1.0.102/functions ./functions
  }
  
  # Raw .deb extractors
-@@ -950,7 +950,7 @@
+@@ -964,7 +954,7 @@
  	esac
  
  	if in_path "$cat_cmd"; then
@@ -19,7 +38,25 @@ diff -u -r ../debootstrap-1.0.102/functions ./functions
  	else
  		error 1 UNPACKCMDUNVL "Extracting %s requires the %s command, which is not available" "$pkg" "$cat_cmd"
  	fi
-@@ -1165,7 +1165,6 @@
+@@ -1020,7 +1010,7 @@
+ ); }
+ 
+ in_target_nofail () {
+-	if ! PATH=/sbin:/usr/sbin:/bin:/usr/bin eval "$CHROOT_CMD \"\$@\"" 2>/dev/null; then
++	if ! PATH=$PATH:/sbin:/usr/sbin:/bin:/usr/bin $CHROOT_CMD "$@" 2>/dev/null; then
+ 		true
+ 	fi
+ 	return 0
+@@ -1032,7 +1022,7 @@
+ 	msg="$2"
+ 	arg="$3"
+ 	shift; shift; shift
+-	if ! PATH=/sbin:/usr/sbin:/bin:/usr/bin eval "$CHROOT_CMD \"\$@\""; then
++	if ! PATH=$PATH:/sbin:/usr/sbin:/bin:/usr/bin $CHROOT_CMD "$@"; then
+ 		warning "$code" "$msg" "$arg"
+ 		# Try to point user at actual failing package.
+ 		msg="See %s for details"
+@@ -1184,7 +1174,6 @@
  			return 0
  		fi
  
