fix formatting

diff --git a/packages/termux-tools/pkg b/packages/termux-tools/pkg
--- a/packages/termux-tools/pkg
+++ b/packages/termux-tools/pkg
@@ -14,26 +14,27 @@ show_help() {
 	echo '  search <query>'
 	echo '  show <packages>'
 	echo '  uninstall <packages>'
-	echo '  update'
 	echo '  upgrade'
 	exit 1
 }
 
 assert_not_root() {
-  if [ $(id -u) -eq 0 ]
-  then
-    echo "This must NOT be run as root as it will break your environment (root will be required for nearly everything due to changed file permissions)"
-    exit 1
-  fi
+	if [ $(id -u) -eq 0 ]; then
+		echo "This must NOT be run as root as it will break your environment (root will be required for nearly everything due to changed file permissions)"
+		exit 1
+	fi
 }
 
-check_pkgcache(){
-  if [ -z "$(find @TERMUX_PREFIX@/var/cache/apt/pkgcache.bin -mmin -5)" ]; then
-    apt update
-  fi
+check_pkgcache() {
+	if [ -z "$(find @TERMUX_PREFIX@/var/cache/apt/pkgcache.bin -mmin -5)" ]; then
+		apt update
+	fi
 }
 
-if [ $# = 0 ]; then show_help; fi
+if [ $# = 0 ]; then
+	show_help
+fi
+
 CMD="$1"
 shift 1
 
@@ -50,4 +51,3 @@ case "$CMD" in
 	up*) assert_not_root; apt update; apt full-upgrade "$@";;
 	*) echo "Unknown command: '$CMD' (run 'pkg help' for usage information)";;
 esac
-
