xfce4-session: fix issue that prevents `startxfce4` from starting
This commit should fix issue when startxfce4 doesn't detect a DISPLAY
variable and exits non-zero code, fixes #734

diff --git a/x11-packages/xfce4-session/disable-xinit-null-display.patch b/x11-packages/xfce4-session/disable-xinit-null-display.patch
--- a/x11-packages/xfce4-session/disable-xinit-null-display.patch
+++ b/x11-packages/xfce4-session/disable-xinit-null-display.patch
@@ -1,20 +1,21 @@
-diff -uNr xfce4-session-4.16.0.mod/scripts/startxfce4.in xfce4-session-4.16.0/scripts/startxfce4.in
---- xfce4-session-4.16.0.mod/scripts/startxfce4.in	2016-05-02 21:02:14.000000000 +0000
-+++ xfce4-session-4.16.0/scripts/startxfce4.in	2022-03-22 03:38:13.853954163 +0000
-@@ -89,14 +89,9 @@
+diff -uNr xfce4-session-4.16.0/scripts/startxfce4.in xfce4-session-4.16.0.mod/scripts/startxfce4.in
+--- xfce4-session-4.16.0/scripts/startxfce4.in	2016-05-02 21:02:14.000000000 +0000
++++ xfce4-session-4.16.0.mod/scripts/startxfce4.in	2022-04-12 08:25:51.362449242 +0000
+@@ -88,14 +88,9 @@
+ fi
  export XDG_CONFIG_DIRS
  
- if test "x$DISPLAY" = "x"
-+  echo "$0: Failed to connect to display"
-+  exit 1
- then
+-if test "x$DISPLAY" = "x"
+-then
 -  echo "$0: Starting X server"
 -  prog=xinit
 -
 -  if test ! "x$XDG_VTNR" = "x"; then
 -    SERVERRC="vt$XDG_VTNR $SERVERRC"
 -  fi
--else
++if test "x$DISPLAY" = "x"; then
++  echo "$0: Failed to connect to display"
++  exit 2
+ else
    echo "$0: X server already running on display $DISPLAY"
    prog=/bin/sh
- fi
