bump(x11/xfce4-session): 4.20.0
* Remove unnecessary dont-update-icon-cache.patch file.
* Add required configure options explicitly for strict dependency checking.

diff --git a/x11-packages/xfce4-session/disable-xinit-null-display.patch b/x11-packages/xfce4-session/disable-xinit-null-display.patch
--- a/x11-packages/xfce4-session/disable-xinit-null-display.patch
+++ b/x11-packages/xfce4-session/disable-xinit-null-display.patch
@@ -1,21 +1,20 @@
-diff -uNr xfce4-session-4.16.0/scripts/startxfce4.in xfce4-session-4.16.0.mod/scripts/startxfce4.in
---- xfce4-session-4.16.0/scripts/startxfce4.in	2016-05-02 21:02:14.000000000 +0000
-+++ xfce4-session-4.16.0.mod/scripts/startxfce4.in	2022-04-12 08:25:51.362449242 +0000
-@@ -88,14 +88,9 @@
- fi
- export XDG_CONFIG_DIRS
+--- a/scripts/startxfce4.in
++++ b/scripts/startxfce4.in
+@@ -114,14 +114,9 @@
  
--if test "x$DISPLAY" = "x"
--then
--  echo "$0: Starting X server"
--  prog=xinit
+ if test "x$XFCE4_SESSION_COMPOSITOR" = "x"
+ then
+-  if test "x$DISPLAY" = "x"
+-  then
+-    echo "$0: Starting X server"
+-    prog=xinit
 -
--  if test ! "x$XDG_VTNR" = "x"; then
--    SERVERRC="$SERVERRC vt$XDG_VTNR"
--  fi
-+if test "x$DISPLAY" = "x"; then
-+  echo "$0: Failed to connect to display"
-+  exit 2
- else
-   echo "$0: X server already running on display $DISPLAY"
-   prog=/bin/sh
+-    if test ! "x$XDG_VTNR" = "x"; then
+-      SERVERRC="$SERVERRC vt$XDG_VTNR"
+-    fi
++  if test "x$DISPLAY" = "x"; then
++    echo "$0: Failed to connect to display"
++    exit 2
+   else
+     echo "$0: X server already running on display $DISPLAY"
+     prog=/bin/sh
