mariadb: update to 10.4.12
ARM builds should be now fixed.

diff --git a/packages/mariadb/scripts-mysql_install_db.sh.patch b/packages/mariadb/scripts-mysql_install_db.sh.patch
--- a/packages/mariadb/scripts-mysql_install_db.sh.patch
+++ b/packages/mariadb/scripts-mysql_install_db.sh.patch
@@ -1,36 +1,7 @@
-diff -uNr mariadb-10.4.6/scripts/mysql_install_db.sh mariadb-10.4.6.mod/scripts/mysql_install_db.sh
---- mariadb-10.4.6/scripts/mysql_install_db.sh	2019-06-18 01:00:32.000000000 +0300
-+++ mariadb-10.4.6.mod/scripts/mysql_install_db.sh	2019-08-04 21:52:11.299044998 +0300
-@@ -1,16 +1,16 @@
- #!/bin/sh
- # Copyright (c) 2000, 2013, Oracle and/or its affiliates.
- # Copyright (c) 2009, 2013, Monty Program Ab
--# 
-+#
- # This program is free software; you can redistribute it and/or modify
- # it under the terms of the GNU General Public License as published by
- # the Free Software Foundation; version 2 of the License.
--# 
-+#
- # This program is distributed in the hope that it will be useful,
- # but WITHOUT ANY WARRANTY; without even the implied warranty of
- # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
- # GNU General Public License for more details.
--# 
-+#
- # You should have received a copy of the GNU General Public License
- # along with this program; if not, write to the Free Software
- # Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1335  USA
-@@ -76,7 +76,7 @@
-   --force              Causes mysql_install_db to run even if DNS does not
-                        work.  In that case, grant table entries that
-                        normally use hostnames will use IP addresses.
--  --help               Display this help and exit.                     
-+  --help               Display this help and exit.
-   --ldata=path         The path to the MariaDB data directory. Same as
-                        --datadir.
-   --no-defaults        Don't read default options from any option file.
-@@ -453,37 +453,10 @@
+diff -u -r ../mariadb-10.4.12/scripts/mysql_install_db.sh ./scripts/mysql_install_db.sh
+--- ../mariadb-10.4.12/scripts/mysql_install_db.sh	2020-01-26 20:43:53.000000000 +0000
++++ ./scripts/mysql_install_db.sh	2020-02-15 23:19:05.141979000 +0000
+@@ -466,42 +466,8 @@
      fi
      chmod 700 "$dir"
    fi
@@ -46,25 +17,30 @@ diff -uNr mariadb-10.4.6/scripts/mysql_install_db.sh mariadb-10.4.6.mod/scripts/
 -  fi
  done
  
- if test -n "$user"
- then
--  chown $user "$pamtooldir/auth_pam_tool_dir"
--  if test $? -ne 0
+-if test -n "$user"
+-then
+-  if test -z "$srcdir" -a "$in_rpm" -eq 0
 -  then
--      echo "Cannot change ownership of the '$pamtooldir/auth_pam_tool_dir' directory"
--      echo " to the '$user' user. Check that you have the necessary permissions and try again."
--      exit 1
--  fi
--  if test -z "$srcdir"
--  then
--    chown 0 "$pamtooldir/auth_pam_tool_dir/auth_pam_tool"
+-    chown 0 "$pamtooldir/auth_pam_tool_dir/auth_pam_tool" && \
+-    chmod 04755 "$pamtooldir/auth_pam_tool_dir/auth_pam_tool"
 -    if test $? -ne 0
 -    then
 -        echo "Couldn't set an owner to '$pamtooldir/auth_pam_tool_dir/auth_pam_tool'."
--        echo " It must be root, the PAM authentication plugin doesn't work otherwise.."
+-        echo "It must be root, the PAM authentication plugin doesn't work otherwise.."
+-        echo
+-    fi
+-    chown $user "$pamtooldir/auth_pam_tool_dir" && \
+-    chmod 0700 "$pamtooldir/auth_pam_tool_dir"
+-    if test $? -ne 0
+-    then
+-        echo "Cannot change ownership of the '$pamtooldir/auth_pam_tool_dir' directory"
+-        echo "to the '$user' user. Check that you have the necessary permissions and try again."
 -        echo
 -    fi
 -  fi
-   args="$args --user=$user"
- fi
- 
+-  args="$args --user=$user"
+-fi
+-
+ if test -f "$ldata/mysql/user.frm"
+ then
+     echo "mysql.user table already exists!"
