chore: switch to monorepo

diff --git a/.github/workflows/packages.yml b/.github/workflows/packages.yml
--- a/.github/workflows/packages.yml
+++ b/.github/workflows/packages.yml
@@ -5,10 +5,14 @@ on:
     branches:
     - master
     paths:
-    - 'packages/**'
+    - 'main/**'
+    - 'x11/**'
+    - 'root/**'
   pull_request:
     paths:
-    - 'packages/**'
+    - 'main/**'
+    - 'x11/**'
+    - 'root/**'
   workflow_dispatch:
     inputs:
       packages:
@@ -27,7 +31,7 @@ jobs:
       fail-fast: false
     steps:
     - name: Clone repository
-      uses: actions/checkout@v2
+      uses: actions/checkout@v3
       with:
         fetch-depth: 1000
     - name: Gather build summary
@@ -73,58 +77,69 @@ jobs:
             docker build -t termux/package-builder:latest .
             cd ..
           fi
-          # Parse changed files and identify new packages and deleted packages.
-          # Create lists of those packages that will be passed to upload job for
-          # further processing.
-          while read -r file; do
-            if ! [[ $file == packages/* ]]; then
-              # This file does not belong to a package, so ignore it
-              continue
-            fi
-            if [[ $file =~ ^packages/([.a-z0-9+-]*)/([.a-z0-9+-]*).subpackage.sh$ ]]; then
-              # A subpackage was modified, check if it was deleted or just updated
-              pkg=${BASH_REMATCH[1]}
-              subpkg=${BASH_REMATCH[2]}
-              if [ ! -f "packages/${pkg}/${subpkg}.subpackage.sh" ]; then
-                echo "$subpkg" >> ./deleted_packages.txt
+
+          for repo in main x11 root; do
+            # Parse changed files and identify new packages and deleted packages.
+            # Create lists of those packages that will be passed to upload job for
+            # further processing.
+            while read -r file; do
+              if ! [[ $file == $repo/* ]]; then
+                # This file does not belong to a package, so ignore it
+                continue
               fi
-            elif [[ $file =~ ^packages/([.a-z0-9+-]*)/.*$ ]]; then
-              # package, check if it was deleted or updated
-              pkg=${BASH_REMATCH[1]}
-              if [ ! -d "packages/${pkg}" ]; then
-                echo "$pkg" >> ./deleted_packages.txt
-              else
-                echo "$pkg" >> ./built_packages.txt
-                # If there are subpackages we want to create a list of those
-                # as well
-                for file in $(find "packages/${pkg}/" -maxdepth 1 -type f -name \*.subpackage.sh | sort); do
-                  echo "$(basename "${file%%.subpackage.sh}")" >> ./built_subpackages.txt
-                done
+              if [[ $file =~ ^$repo/([.a-z0-9+-]*)/([.a-z0-9+-]*).subpackage.sh$ ]]; then
+                # A subpackage was modified, check if it was deleted or just updated
+                pkg=${BASH_REMATCH[1]}
+                subpkg=${BASH_REMATCH[2]}
+                if [ ! -f "${repo}/${pkg}/${subpkg}.subpackage.sh" ]; then
+                  echo "$subpkg" >> ./deleted_$repo_packages.txt
+                fi
+              elif [[ $file =~ ^$repo/([.a-z0-9+-]*)/.*$ ]]; then
+                # package, check if it was deleted or updated
+                pkg=${BASH_REMATCH[1]}
+                if [ ! -d "${repo}/${pkg}" ]; then
+                  echo "$pkg" >> ./deleted_$repo_packages.txt
+                else
+                  echo "$pkg" >> ./built_$repo_packages.txt
+                  # If there are subpackages we want to create a list of those
+                  # as well
+                  for file in $(find "${repo}/${pkg}/" -maxdepth 1 -type f -name \*.subpackage.sh | sort); do
+                    echo "$(basename "${file%%.subpackage.sh}")" >> ./built_$repo_subpackages.txt
+                  done
+                fi
               fi
-            fi
-          done<<<${CHANGED_FILES}
+            done<<<${CHANGED_FILES}
+          done
         else
           for pkg in ${{ github.event.inputs.packages }}; do
-            echo "$pkg" >> ./built_packages.txt
-            for subpkg in $(find "packages/${pkg}/" -maxdepth 1 -type f -name \*.subpackage.sh | sort); do
-              echo "$(basename "${subpkg%%.subpackage.sh}")" >> ./built_subpackages.txt
+            for repo in main x11 root; do
+              if [ -d "${repo}/${pkg}" ]; then
+                echo "$pkg" >> ./built_$repo_packages.txt
+                for subpkg in $(find "${repo}/${pkg}/" -maxdepth 1 -type f -name \*.subpackage.sh | sort); do
+                  echo "$(basename "${subpkg%%.subpackage.sh}")" >> ./built_$repo_subpackages.txt
+                done
+              else
+                echo "Package '${pkg}' not found in any of the repo"
+              fi
             done
           done
         fi
 
-        # Fix so that lists do not contain duplicates
-        if [ -f ./built_packages.txt ]; then
-          uniq ./built_packages.txt > ./built_packages.txt.tmp
-          mv ./built_packages.txt.tmp ./built_packages.txt
-        fi
-        if [ -f ./built_subpackages.txt ]; then
-          uniq ./built_subpackages.txt > ./built_subpackages.txt.tmp
-          mv ./built_subpackages.txt.tmp ./built_subpackages.txt
-        fi
-        if [ -f ./deleted_packages.txt ]; then
-          uniq ./deleted_packages.txt > ./deleted_packages.txt.tmp
-          mv ./deleted_packages.txt.tmp ./deleted_packages.txt
-        fi
+        for repo in main x11 root; do
+          # Fix so that lists do not contain duplicates
+          if [ -f ./built_$repo_packages.txt ]; then
+            uniq ./built_$repo_packages.txt > ./built_$repo_packages.txt.tmp
+            mv ./built_$repo_packages.txt.tmp ./built_$repo_packages.txt
+          fi
+          if [ -f ./built_$repo_subpackages.txt ]; then
+            uniq ./built_$repo_subpackages.txt > ./built_$repo_subpackages.txt.tmp
+            mv ./built_$repo_subpackages.txt.tmp ./built_$repo_subpackages.txt
+          fi
+          if [ -f ./deleted_$repo_packages.txt ]; then
+            uniq ./deleted_$repo_packages.txt > ./deleted_$repo_packages.txt.tmp
+            mv ./deleted_$repo_packages.txt.tmp ./deleted_$repo_packages.txt
+          fi
+        done
 
     - name: Free additional disk space (if necessary)
       run: |
@@ -136,45 +151,63 @@ jobs:
           sudo rm -rf /opt/hostedtoolcache /usr/local /usr/share/dotnet /usr/share/swift
         fi
 
-    - name: Build
+    - name: Lint packages
       run: |
-        if [ -f ./built_packages.txt ]; then
-          ./scripts/lint-packages.sh $(cat ./built_packages.txt | awk '{print "packages/"$1"/build.sh"}')
-          ./scripts/run-docker.sh ./build-package.sh -I -a ${{ matrix.target_arch }} $(cat ./built_packages.txt)
-        fi
+        local package_recipes=
+        for repo in main x11 root; do
+          if [ -f ./built_$repo_packages.txt ]; then
+            package_recipes+=$(cat ./built_$repo_packages.txt | repo=$repo awk '{print ENVIRON["repo"]"/"$1"/build.sh"}')
+          fi
+        done
+
+        ./scripts/lint-packages.sh $package_recipes
+
+    - name: Build packages
+      run: |
+        local packages=
+        for repo in main x11 root; do
+          if [ -f ./built_$repo_packages.txt ]; then
+            packages+=$(cat ./build_$repo_packages.txt)
+          fi
+        done
+
+        ./scripts/run-docker.sh ./build-package.sh -I -a ${{ matrix.target_arch }} $packages
 
     - name: Generate build artifacts
       if: always()
       run: |
-        mkdir -p debs
         test -d termux-packages/output && mv termux-packages/output/* ./output/
 
-        # Put package lists into directory with *.deb files so they will be transferred to
-        # upload job.
-        test -f ./built_packages.txt && mv ./built_packages.txt ./debs/
-        test -f ./built_subpackages.txt && cat ./built_subpackages.txt >> ./debs/built_packages.txt \
-          && rm ./built_subpackages.txt
-        test -f ./deleted_packages.txt && mv ./deleted_packages.txt ./debs/
+        for repo in main x11 root; do
+          mkdir debs
+          # Put package lists into directory with *.deb files so they will be transferred to
+          # upload job.
+          test -f ./built_$repo_packages.txt && mv ./built_repo_packages.txt ./debs/built_packages.txt
+          test -f ./built_$repo_subpackages.txt && cat ./built_repo_subpackages.txt >> ./debs/built_packages.txt \
+            && rm ./built_$repo_subpackages.txt
+          test -f ./deleted_$repo_packages.txt && mv ./deleted_$repo_packages.txt ./debs/deleted_packages.txt
 
-        # Move only debs from built_packages into debs/ folder before
-        # creating an archive.
-        while read -r pkg; do
-          # Match both $pkg.deb and $pkg-static.deb.
-          find output \( -name "$pkg_*.deb" -o -name "$pkg-static_*.deb" \) -type f -print0 | xargs -0r mv -t debs/
-        done < <(cat ./debs/built_packages.txt)
+          # Move only debs from built_packages into debs/ folder before
+          # creating an archive.
+          while read -r pkg; do
+            # Match both $pkg.deb and $pkg-static.deb.
+            find output \( -name "$pkg_*.deb" -o -name "$pkg-static_*.deb" \) -type f -print0 | xargs -0r mv -t debs/
+          done < <(cat ./debs/built_packages.txt)
 
-        # Files containing certain symbols (e.g. ":") will cause failure in actions/upload-artifact.
-        # Archiving *.deb files in a tarball to avoid issues with uploading.
-        tar cf artifacts/debs-${{ matrix.target_arch }}-${{ github.sha }}.tar debs
+          # Files containing certain symbols (e.g. ":") will cause failure in actions/upload-artifact.
+          # Archiving *.deb files in a tarball to avoid issues with uploading.
+          tar cf artifacts/debs-${repo}-${{ matrix.target_arch }}-${{ github.sha }}.tar debs
+          rm -r debs/
+        done
     - name: Checksums for built *.deb files
       if: always()
       run: |
         find debs -type f -name "*.deb" -exec sha256sum "{}" \; | sort -k2
     - name: Store *.deb files
       if: always()
-      uses: actions/upload-artifact@v2
+      uses: actions/upload-artifact@v3
       with:
-        name: termux-packages-${{ matrix.target_arch }}-${{ github.sha }}
+        name: debs-${{ matrix.target_arch }}-${{ github.sha }}
         path: ./artifacts
 
   upload:
@@ -183,9 +216,9 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     - name: Clone repository
-      uses: actions/checkout@v2
+      uses: actions/checkout@v3
     - name: Get *.deb files
-      uses: actions/download-artifact@v2
+      uses: actions/download-artifact@v3
       with:
         path: ./
     - name: Upload to packages.termux.org
@@ -200,41 +233,48 @@ jobs:
 
         source scripts/aptly_api.sh
 
-        for archive in termux-packages-*/*.tar; do
-          tar xf "$archive"
+        for repo in main x11 root; do
+          export REPOSITORY_NAME=termux-$repo
+
+          for archive in debs-*/debs-$repo-{aarch64,arm,i686,x86_64}-${{ github.sha }}.tar; do
+            tar xf "$archive"
+          done
+
+          # Upload file to temporary directory.
+          uploaded_files=false
+          shopt -s nullglob
+          for filename in $(cat debs/built_packages.txt | sed -E 's/(..*)/debs\/\1_\*.deb debs\/\1-static_\*.deb/g'); do
+            if ! aptly_upload_file "$filename"; then
+              exit 1
+            fi
+
+            uploaded_files=true
+          done
+          shopt -u nullglob
+  
+          # Publishing repository changes.
+          if [ "$uploaded_files" = "true" ]; then
+            if ! aptly_add_to_repo; then
+              exit 1
+            fi
+
+            # Usually temporary directory is deleted automatically, but in certain cases it is left.
+            aptly_delete_dir
+
+            # Final part to make changes appear in web root.
+            if ! aptly_publish_repo; then
+              exit 1
+            fi
+          fi
+
+          # Delete the debs folder in order to not upload packages from one repo to other
+          # TODO(@thunder-coding): Perhaps it would make sense to make use of tar's `-C` option in order to prevent extracting the archives twice
+          rm -rf debs/
         done
-
-        # Upload file to temporary directory.
-        uploaded_files=false
-        shopt -s nullglob
-        for filename in $(cat debs/built_packages.txt | sed -E 's/(..*)/debs\/\1_\*.deb debs\/\1-static_\*.deb/g'); do
-          if ! aptly_upload_file "$filename"; then
-            exit 1
-          fi
-
-          uploaded_files=true
-        done
-        shopt -u nullglob
-
-        # Publishing repository changes.
-        if [ "$uploaded_files" = "true" ]; then
-          if ! aptly_add_to_repo; then
-            exit 1
-          fi
-
-          # Usually temporary directory is deleted automatically, but in certain cases it is left.
-          aptly_delete_dir
-
-          # Final part to make changes appear in web root.
-          if ! aptly_publish_repo; then
-            exit 1
-          fi
-        fi
     - name: Upload to grimler.se
       # Run even if upload to packages.termux.org failed:
       if: always()
       env:
-        REPOSITORY_NAME: termux-main
         REPOSITORY_DISTRIBUTION: stable
         REPOSITORY_URL: https://aptly-api.grimler.se
       run: |
@@ -243,30 +283,41 @@ jobs:
 
         source scripts/aptly_api.sh
 
-        # Upload file to temporary directory.
-        uploaded_files=false
-        shopt -s nullglob
-        for filename in $(cat debs/built_packages.txt | sed -E 's/(..*)/debs\/\1_\*.deb debs\/\1-static_\*.deb/g'); do
-          if ! aptly_upload_file "$filename"; then
-            exit 1
-          fi
 
-          uploaded_files=true
+        for repo in main x11 root; do
+          export REPOSITORY_NAME=termux-$repo
+
+          for archive in debs-*/debs-$repo-{aarch64,arm,i686,x86_64}-${{ github.sha }}.tar; do
+            tar xf "$archive"
+          done
+
+          # Upload file to temporary directory.
+          uploaded_files=false
+          shopt -s nullglob
+          for filename in $(cat debs/built_packages.txt | sed -E 's/(..*)/debs\/\1_\*.deb debs\/\1-static_\*.deb/g'); do
+            if ! aptly_upload_file "$filename"; then
+              exit 1
+            fi
+
+            uploaded_files=true
+          done
+          shopt -u nullglob
+
+          # Publishing repository changes.
+          if [ "$uploaded_files" = "true" ]; then
+            if ! aptly_add_to_repo; then
+              exit 1
+            fi
+
+            # Usually temporary directory is deleted automatically, but in certain cases it is left.
+            aptly_delete_dir
+
+            # grimler.se mirror is signed manually, can't publish
+            # through CI
+            # if ! aptly_publish_repo; then
+            #   exit 1
+            # fi
+          fi
+          # Delete the debs folder in order to not upload packages from one repo to other
+          rm -rf debs/
         done
-        shopt -u nullglob
-
-        # Publishing repository changes.
-        if [ "$uploaded_files" = "true" ]; then
-          if ! aptly_add_to_repo; then
-            exit 1
-          fi
-
-          # Usually temporary directory is deleted automatically, but in certain cases it is left.
-          aptly_delete_dir
-
-          # grimler.se mirror is signed manually, can't publish
-          # through CI
-          # if ! aptly_publish_repo; then
-          #   exit 1
-          # fi
-        fi
