ci(packages): only refuse to proceed if the force push is not on PR
Previously it used to check for force push for PRs as well which was not
desired. For dev and dev/* branches, it'll not straight up error out,
but try to build anyway and give a warning about it

diff --git a/.github/workflows/packages.yml b/.github/workflows/packages.yml
--- a/.github/workflows/packages.yml
+++ b/.github/workflows/packages.yml
@@ -54,11 +54,17 @@ jobs:
           # https://docs.github.com/en/webhooks/webhook-events-and-payloads#push
           OLD_COMMIT=$(jq --raw-output .before "$GITHUB_EVENT_PATH")
           HEAD_COMMIT=$(jq --raw-output .after "$GITHUB_EVENT_PATH")
-          if ! git log "$OLD_COMMIT" 2> /dev/null; then
-            echo "Force push detected on main branch. Unable to proceed."
-            exit 1
-          fi
           if [ "$BASE_COMMIT" = "null" ]; then
+            if ! git log "$OLD_COMMIT" 2> /dev/null
+              if [ "$(git branch --show-current)" = "master" ]; then
+                echo "Force push detected on master branch. Unable to proceed."
+                exit 1
+              else
+                echo "::warning:: Force push detected on non-master branch. Trying to proceed at any cost but may not work as expected."
+                OLD_COMMIT=$(jq --raw-output .commits[0].id "$GITHUB_EVENT_PATH")
+                echo "::warning:: OLD_COMMIT is set to $OLD_COMMIT which may not be correct if you have pushed more than 20 commits."
+              fi
+            fi
             if [ "$OLD_COMMIT" = "$HEAD_COMMIT" ]; then
               # Single-commit push.
               echo "Processing commit: ${HEAD_COMMIT}"
